# NumPy Random 
> Assignment for Module 52465 Programming for Data Analysis

---
## Table of Contents

- [Introduction]
- [NumPy]
- [Installing NumPy]
- [numpy.random]


---
### Introduction

This project sets out to examine the `numpy.random` package and some of it's distributions, through a review of documentation on the package and an analysis of data sets using it's operations. 

---
### NumPy
![image.png](https://scikit-learn.org/stable/_static/ml_map.png

NumPy, short for Numerical Python, is a principal library in Python. Created in 2005, by Travis Oliphant, this open-source software is used for mathimatical, scientific, engineering and data science programming. 

The NumPy library provides tools to work efficiently and effectively with large quantities of numerical data.
To work with a collection of elements (an array) in Python we use lists. Lists are effective when working with varying types and small amounts of data but how Python stores lists is slow and resources heavy.

A Python list is an array of signposts pointing to a location that has information about an element. This can be sufficient when working with smaller quantities or varying types of data but is a slow and resource heavy process for larger or complex work.

#### Why use NumPy over Python Lists?
NumPy’s ndarrays are homogenous (of a single type) n-dimensional (vectorised) array objects that are stored in one continuous place they can be accessed, processed and manipulated much more efficiently. Additionally, the NumPy library provides powerful multidimensional array and matrix data structures and a large collection of high-level mathematical functions to operate on them. 

The NumPy library also offers classes and functions to test linear algebra operations, Fourier series and random number generation. The library is used extensively when working with numerical data in Python and other Python libraries such as Pandas, Matplotlib and SciPy are built on it. 

## Installing NumPy

The only prerequisite for NumPy is Python. Installation of the Anaconda Distribution is an easy way to obtain this as it includes Python, NumPy, and other commonly used packages. Full details of which are available here: https://docs.anaconda.com/anaconda/install/

NumPy can also be installed with conda, with pip, or with a package manager on macOS and Linux. 

#### Installing with conda
If you use `conda` you can install it with
`conda install numpy`

#### Installing via Pip
If you use `pip` you can install with 
`pip install numpy`

#### Install System-wide via a Package Manager
The NumPy documentation offers detailed guides on how to install NumPy for Linux and Mac users.
This information is available here: 
https://numpy.org/install/

#### Import of NumPy Library

In [2]:
# This imports the libraries (NumPy and MatPlotLib) that will be used in this notebook
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### numpy.random
Random numbers (numbers that cannot be logically predicted) have many uses such as the generation of encryption keys, to prevent selection bias in experimentation and the simulation of complex models and studies.

To generate a truly random number a source of true randomness is needed. Often this is a physical input like a key stroke, or a mouse click. In programming algorithms are used to generate random numbers. Algorithms adhere to a set of rules to generate random numbers. While these numbers appear close to truly random numbers they are generated through a deterministic process (where all the data required to determine the outcome is known in advance) making them pseudorandom. 

The standard Python library offers a module random that includes functions to generate random numbers with a few basic distributions. In contrast to this the NumPy library offers the `numpy.random` module which allows for the generation of arrays of random numbers, using a wide selection of distributions and across different intervals.

NumPy’s random sampling routines can be classified in four ways
- Simple Random Data
- Permutations
- Distributions
- Random Generator 

#### Simple Random Data
NumPy’s Simple Random Data Routines produce randomly generated numbers as defined by the user.

This could be generating a single random integer:

In [3]:
x = np.random.randint(100) # Here we set the range of values for the integer to be selected from. 

print(x)

75


This can be tested by re-running the above code or by changing the range of values to generate the random integar from:

In [12]:
x = np.random.randint(1000) # Here we set the range of values for the integer to be selected from. 

print(x)

886


Or used to generate a random float using `rand()`

In [13]:
x = np.random.rand(5) # Here we set the number of float values to be returned as 5.
                        # As no range of values is set the module will return float values between 0.0 and 1.0 
                        #  but not including 1.0
                        
print (x)

[0.20184672 0.34224609 0.22827787 0.24597548 0.47154685]


The randint() function can also take the input of 2 integers as a range of values and returns an output of a random integer value within the range provided.

In [15]:
Random_1 = np.random.randint(0, 10)  # Here we set the range of values for the integer to be selected from.

print("Random number between 0 and 10 is % s" % (Random_1))

Random number between 0 and 10 is 8


The `randint()` function can also take the input of 2 integers as a range of values and returns an output of a random integer value within the range provided:

In [14]:
Random_2 = np.random.randint(0, 10)  # Here we set the range of values for the integer to be selected from.

print("Random number between 0 and 10 is % s" % (Random_2))

Random number between 0 and 10 is 1


Whether they are poistive or negative:

In [16]:
Random_3 = np.random.randint(-100, -10)  # Here we set a negative range of values for the integer to be selected from.

print("Random number between -100 and -10 is % s" % (Random_3))

Random number between -10 and -1 is -3


Characters/String can't be used as parameters in the `randint()` function:

In [20]:
Random_4 = np.random.randint(a, z) 
print("Random letter between a and z is % s" % (Random_4)) 

NameError: name 'a' is not defined

Neither can floating point values:

In [24]:
Random_5 = np.random.randint(1.32, 1.40) 
print("Random letter between 1.32 and 1.40 is % s" % (Random_5)) 

ValueError: low >= high

Having established that `random.randint()` can generate single random integers and floats let’s use this information to look at arrays.

By including a `size` parameter in the `randint()` function the size of the array can be specified.
This could be a 1-dimensional array:

In [12]:
Random_6 = np.random.randint(100, size=(5)) # Here we are requesting 5 random integers between 0 and 100

print("Here are the random integars you have requested % s" % (Random_6))

Here are the random integars you have requested [60 19 88 58 60]


Or multidimensional array:

In [14]:
Random_7 = np.random.randint(100, size=(4, 10)) # Here we are requesting random integers between 0 and 100
                                                # To be presented in 4 rows each containing 10 integers

print("Here are the random integars you have requested % s" % (Random_7))

Here are the random integars you have requested [[30  1 36 85 87 71 95 93 61 72]
 [31 61 27 36 62 29 14 92 71 95]
 [81 68 45 12 53 50 29 72 98 48]
 [79 65 81 28 21 48 56 35 31 45]]


The `rand` function allows for the creation of arrays using floats.
Similarly, to the `randint` function the inclusion of a size parameter determines the shape of the array.
Again this can be an 1-dimensional array:

In [15]:
Random_8 = np.random.rand(5)

print("Here are the random integars you have requested % s" % (Random_8))

Here are the random integars you have requested [0.9219271  0.94751086 0.72183418 0.03167643 0.971647  ]


Or a multidimensional array:

In [16]:
Random_9 = np.random.rand(5)

print("Here are the random floats you have requested % s" % (Random_9))

Here are the random floats you have requested [0.20933916 0.54152208 0.06934608 0.22846674 0.57009601]


Where `rand` and `randint` can generate arrays from a range of specified values `choice` can generate an array from an array.

`choice` can return a single random value from the provided array:

In [4]:
Choice_1 = np.random.choice([5, 6, 7, 8]) # Here we are requesting that one of the presented values
                                            # from the provided array is randomly selected to be returned.

print("The randomly selected value from the array provided is: % s" % (Choice_1))

The randomly selected value from the array provided is: 7


Or generate a multi-dimensional array consisting of the values from within the array provided:

In [5]:
Choice_2 = np.random.choice([5, 6, 7, 8], size=(2, 4)) # Here we are requesting the return of an array
                                                        # with the size and shape we have defined
                                                            # from the provided array

print("Here is the array you requested from the details and array provided: % s" % (Choice_2))

Here is the array you requested from the details and array provided: [[6 5 5 7]
 [6 8 5 7]]
